apiVersion: v1
kind: Service
metadata:
  name: kafka1
  labels:
    name: kafka1
spec:
  ports:
    - port: 9092
      targetPort: 9092
      name: k1
  selector:
    app: kafka1
  type: LoadBalancer
