apiVersion: v1
kind: Service
metadata:
  name: kafka1
spec:
  type: LoadBalancer
  externalIPs:
    - 172.31.25.198
  ports:
    - port: 9092
      targetPort: 9092
      name: k1
  selector:
    app: kafka1
---
apiVersion: v1
kind: Service
metadata:
  name: kafka2
spec:
  type: LoadBalancer
  externalIPs:
    - 172.31.26.5
  ports:
    - port: 9092
      targetPort: 9092
      name: k1
  selector:
    app: kafka2
