apiVersion: v1
kind: ReplicationController
metadata:
  name: zookeeper1
spec:
  replicas: 1
  selector:
    app: zookeeper1
  template:
    metadata:
      name: zookeeper1
      labels:
        app: zookeeper1
    spec:
      containers:
      - name: zookeeper1
        image: confluentinc/cp-zookeeper:4.0.1
        ports:
        - containerPort: 2181
        - containerPort: 2888
        - containerPort: 3888
        env:
        - name: ZOOKEEPER_SERVER_ID
          value: "1"
        - name: ZOOKEEPER_TICK_TIME
          value: "2000"
        - name: ZOOKEEPER_CLIENT_PORT
          value: "2181"
        - name: ZOOKEEPER_INIT_LIMIT
          value: "5"
        - name: ZOOKEEPER_SYNC_LIMIT
          value: "2"
        - name: ZOOKEEPER_SERVERS
          value: "zookeeper1:12888:13888;zookeeper2:22888:23888;zookeeper3:32888:33888"
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: zookeeper2
spec:
  replicas: 1
  selector:
    app: zookeeper2
  template:
    metadata:
      name: zookeeper2
      labels:
        app: zookeeper2
    spec:
      containers:
      - name: zookeeper2
        image: confluentinc/cp-zookeeper:4.0.1
        ports:
        - containerPort: 2181
        - containerPort: 2888
        - containerPort: 3888
        env:
        - name: ZOOKEEPER_SERVER_ID
          value: "2"
        - name: ZOOKEEPER_TICK_TIME
          value: "2000"
        - name: ZOOKEEPER_CLIENT_PORT
          value: "2181"
        - name: ZOOKEEPER_INIT_LIMIT
          value: "5"
        - name: ZOOKEEPER_SYNC_LIMIT
          value: "2"
        - name: ZOOKEEPER_SERVERS
          value: "zookeeper1:12888:13888;zookeeper2:22888:23888;zookeeper3:32888:33888"
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: zookeeper3
spec:
  replicas: 1
  selector:
    app: zookeeper3
  template:
    metadata:
      name: zookeeper3
      labels:
        app: zookeeper3
    spec:
      containers:
      - name: zookeeper3
        image: confluentinc/cp-zookeeper:4.0.1
        ports:
        - containerPort: 2181
        - containerPort: 2888
        - containerPort: 3888
        env:
        - name: ZOOKEEPER_SERVER_ID
          value: "3"
        - name: ZOOKEEPER_TICK_TIME
          value: "2000"
        - name: ZOOKEEPER_CLIENT_PORT
          value: "2181"
        - name: ZOOKEEPER_INIT_LIMIT
          value: "5"
        - name: ZOOKEEPER_SYNC_LIMIT
          value: "2"
        - name: ZOOKEEPER_SERVERS
          value: "zookeeper1:12888:13888;zookeeper2:22888:23888;zookeeper3:32888:33888"
